on:
  pull_request_target:
    types: [opened, synchronize, reopened, milestoned, demilestoned]
    branches: 
      - 4.0.x  
jobs:
  milestonecheck:
    permissions: 
      pull-requests: read
    name: PR Milestone Check
    runs-on: ubuntu-latest      
    steps:  
    - name: PR requires a milestone
      run: |
        MILESTONE=$(gh pr view $PR --json milestone -q .milestone)
        if [ $? != 0 ] ; then
            echo "Failed"
            exit 1
        fi
        if [ -z "$MILESTONE" ] ; then
            echo "::notice::Milestone is required"
            exit 2
        fi
        env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR: ${{ github.event.pull_request.html_url }}
